config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  resources :buildings do
    resources :rooms
  end

  get 'my_acs', to: 'dashboard#index', as: "my_acs"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  belongs_to :user
  belongs_to :building_type
  has_many :rooms, dependent: :destroy
  has_many :climate_logs
  private
end

app/models/building_type.rb
class BuildingType < ApplicationRecord

end

app/models/climate_log.rb
class ClimateLog < ApplicationRecord
  belongs_to :building
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :building
  belongs_to :ventilation_type
  has_many :climate_logs, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :validatable

  has_many :buildings, dependent: :destroy
  has_many :rooms, through: :buildings, dependent: :destroy
  belongs_to :user_role
end

app/models/user_role.rb
class UserRole < ApplicationRecord
end

app/models/ventilation_type.rb
class VentilationType < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!,
                :get_all_buildings,
                :get_all_rooms,
                :get_user

  def after_sign_in_path_for(resource_or_scope)
    my_acs_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  private

  def get_all_buildings
    @all_buildings = Building.where(user: current_user)
  end

  def get_all_rooms
    @all_rooms = Room.where(building: @all_buildings)
  end

  def get_user
    @user = current_user
  end

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

  def show
    @building = Building.find(params[:id])
    @outside_temp_array = outside_temp_by_day
    @outside_hum_array = outside_hum_by_day
    # byebug
  end

  private

  def outside_temp_by_day
    ClimateLog.where(building: @building, room: @building.rooms.first).map(&:outside_temp)
  end

  def outside_hum_by_day
    ClimateLog.where(building: @building, room: @building.rooms.first).map(&:outside_humidity)
  end

end

app/controllers/dashboard_controller.rb
  class DashboardController < ApplicationController
  before_action :get_room_count,
                :get_building_count

  def index
    @title = "My Home Keep Dashboard"

    @avg_outside_temp = avg_outside_temp
    @avg_inside_temp = avg_inside_temp

    @total_sqm = total_square_meters

  end

  private

  def get_building_count
    @building_count = @all_buildings.count
  end

  def get_room_count
    @room_count = @all_rooms.count
  end

  def avg_outside_temp
    arr = []
    @all_buildings.each do |x|
      arr << x.outside_temp
    end
    return "#{(arr.reduce(:+) / arr.count).round(1)}"
  end

  def avg_inside_temp
    arr = []
    @all_rooms.each do |x|
      arr << x.temp
    end
    return "#{(arr.reduce(:+) / arr.count).round(1)}"
  end

  def total_square_meters
    arr = []
    @all_rooms.each do |x|
      arr << x.sqm
    end
    return arr.reduce(:+)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def show
    @room = Room.find(params[:id])
    @building = Building.find(params[:building_id])
    @inside_temp_array = inside_temp_by_day
    @inside_hum_array = inside_hum_by_day

    # byebug
  end

  private

  def inside_temp_by_day
    ClimateLog.where(room: @room).map(&:room_temp)
  end

  def inside_hum_by_day
    ClimateLog.where(room: @room).map(&:room_humidity)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    content_tag(:title, @title || "Home Keep: Home Automation Dashboard")
  end

  def buliding_typ_icon(instance)
    type_arr = ["office", "residence", "factory", "storage", "multi-residence", "commercial", "restaurant"]
    icon_arr = ["building", "home", "industry", "warehouse", "hotel", "hand-holding-usd", "utensils"]
    return icon_arr[type_arr.index(instance.building_type.name)]
  end

end

app/views/buildings/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-xs-12 ">
      <h1 class="page_headline"> <%= "#{@user.first_name.capitalize} #{@user.last_name.capitalize}'s Building List" %></h1>
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <div class="list_page_outer">
        <div class="list_page_inner">
          <table class="list_table table-condensed">
            <tr>
              <th>Property Name</th>
              <th>Room Count</th>
              <th>Ambient Temp</th>
              <th class="hidden-xs">Ambient Humidity</th>
              <th class="hidden-xs">Avg. Inside Temp</th>
              <th class="hidden-xs">Avg. Inside Humidity</th>
            </tr>
            <% @all_buildings.each do |building| %>
              <tr>
                <td><%= link_to building.name.split.map(&:capitalize).join(" "), building_path(building.id) %></td>
                <td><%= @all_rooms.where(building: building).count %></td>
                <td><%= building.outside_temp.round(1) %>°</td>
                <td class="hidden-xs"><%= building.outside_humidity.round(1) %>%</td>
                <td class="hidden-xs">
                  <%= (@all_rooms.where(building: building).sum { |room| room.temp } / @all_rooms.where(building: building).count).round(1) %>°
                </td>
                <td class="hidden-xs">
                  <%= (@all_rooms.where(building: building).sum { |room| room.humidity } / @all_rooms.where(building: building).count).round(1) %>%
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/buildings/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-xs-12 ">
      <h1 class="page_headline"> <%= "#{@building.name.split.map(&:capitalize).join(" ")}'s Room List" %></h1>
      <hr>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= link_to my_acs_path, style: "font-size: 15px;" do %>
        <i class="fas fa-arrow-left"></i> To Dashboard
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-5 col-md-4">
      <div class="building_floorplan_outer">
        <div class="building_floorplan_inner">
          <img src="https://static1.squarespace.com/static/558b0741e4b06f25237894f2/t/5a90cd50c830257a34234405/1519439194245/unfurnished+(87).png?format=1500w" alt="">
        </div>
      </div>
      <hr class="hidden-sm hidden-md hidden-lg hidden-xl">
    </div>

    <div class="col-xs-12 col-sm-7 col-md-8">
      <div class="list_page_outer">
        <div class="list_page_inner">
          <table class="list_table table-condensed">
            <tr>
              <th></th>
              <th class="hidden-xs">Room Size</th>
              <th>Room Temp</th>
              <th>Room Humidity</th>
            </tr>
            <% @all_rooms.where(building: @building).each do |room| %>
              <tr>
                <td><%= link_to room.name.split.map(&:capitalize).join(" "), building_room_path(@building.id, room.id) %></td>
                <td class="hidden-xs"><%= room.sqm %>m2</td>
                <td><%= room.temp.round(1) %>°</td>
                <td><%= room.humidity.round(1) %>%</td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-xs-12 col-sm-5 col-md-4">
      <h5 align="center" style="font-weight: bold; color: rgba(58,130,180,1) !important; text-decoration: underline;">Outside Temp Log: Pasted 30 days</h5>
      <ul>
        <li>Avg. Temperature: <%= "#{(@outside_temp_array.reduce(:+) / @outside_temp_array.count).round(1)}°" %></li>
        <li>Avg. Humidity: <%= "#{(@outside_hum_array.reduce(:+) / @outside_hum_array.count).round(1)}%" %></li>
        <li>High Temperature: <%= "#{@outside_temp_array.sort.pop}°" %></li>
        <li>High Humidity: <%= "#{@outside_hum_array.sort.pop}%" %></li>
      </ul>
    </div>
    <div class="col-xs-12 col-sm-7 col-md-8">
      <div class="bar_chart_container">
        <table>
          <tr>
            <% @outside_temp_array.each do |temp| %>
            <td title='<%= "#{temp}°" %>'>
              <div style='height: <%= "#{((1 - (temp / (@outside_temp_array.sort{ |x,y| y <=> x }.first) )) * 200).to_i}" %>px;'></div>
              <span class="hidden-xs"><%= "#{temp}" %></span>
            </td>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
  </div>

</div>

app/views/dashboard/index.html.erb
<div class="container container_fitter">

  <div class="row">
    <div class="col-xs-12 ">
      <h1 class="page_headline"> Dashboard </h1>
      <hr>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-4 col-md-3 hidden-xs">
      <div class="dashboard_total_container_outer">
        <div class="dashboard_total_container_inner">
          <div class="dashboard_total_upper dashboard_matrix_number">
            <%= @room_count %>
            <h5 align="center">Total # of Rooms</h5>
          </div>
          <div class="dashboard_total_lower dashboard_matrix_number">
            <%= @total_sqm %>
            <h5 align="center">Total Sqm</h5>
          </div>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-sm-8 col-md-9">
      <div class="list_page_inner">
        <table class="list_table table-condensed">
          <tr>
            <th class="hidden-sm hidden-md hidden-lg hidden-xl"></th>
            <th colspan="2" class="hidden-xs">Property</th>
            <th class="hidden-xs">Room Count</th>
            <th>Current<br>Outside Temp</th>
            <th>Current<br>Outside Humidity</th>
            <th class="hidden-xs">Avg<br>Room Temp</th>
            <th class="hidden-xs">Avg<br>Room Humidity</th>
          </tr>
          <% @all_buildings.each do |building| %>
            <tr>
              <td><%= link_to building.name.split.map(&:capitalize).join(" "), building_path(building.id) %></td>
              <td class="hidden-xs"><%= link_to "<i class='fas fa-#{buliding_typ_icon(building)}'></i>".html_safe, building_path(building.id) %></td>
              <td class="hidden-xs"><%= @all_rooms.where(building: building).count %></td>
              <td><%= building.outside_temp %>°</td>
              <td><%= building.outside_humidity %>%</td>

              <td class="hidden-xs"><%= (@all_rooms.where(building: building).sum { |room| room.temp } / @all_rooms.where(building: building).count).round(1) %>°</td>
              <td class="hidden-xs"><%= (@all_rooms.where(building: building).sum { |room| room.humidity } / @all_rooms.where(building: building).count).round(1) %>%</td>
            </tr>
          <% end %>

        </table>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= title %>
    <link rel="icon"
          type="image/png"
          href="<%= image_path("favicon_c.png")  %> ">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/desktop_navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/mobile_navbar' %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="logo-centerer">
    <div class="home_landing_box">
      <%= image_tag "acs_logo_500x165.png", style: "" %>
      <h1 class="brand_font text_border_headliner home_landing_headline">autonomic climate<br>systems</h1>

      <hr>

      <% if user_signed_in? %>
      <% else %>
        <%= link_to new_user_session_path, class: "" do %>
        <button class="btn btn-primary">
          <i class="fas fa-sign-in-alt"></i> <%= t(".sign_in", default: "Log in") %>
        </button>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/rooms/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-xs-12 ">
      <h1 class="page_headline"> <%= "#{@user.first_name.capitalize} #{@user.last_name.capitalize}'s Room List" %></h1>
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <div class="list_page_outer">
        <div class="list_page_inner">
          <table class="list_table table-condensed">
            <tr>
              <th>Room Name</th>
              <th>Property Name</th>
              <th>Ambient Temp</th>
              <th class="hidden-xs">Ambient Humidity</th>
              <th class="hidden-xs">Inside Temp</th>
              <th class="hidden-xs">Inside Humidity</th>
            </tr>
            <% @all_rooms.each do |room| %>
              <tr>
                <td><%= room.name.capitalize %></td>
                <td><%= link_to @all_buildings.find(room.building_id).name.capitalize, building_path(room.building_id) %></td>
                <td><%= @all_buildings.find(room.building_id).outside_temp.round(1) %>°</td>
                <td class="hidden-xs"><%= @all_buildings.find(room.building_id).outside_humidity.round(1) %>%</td>
                <td class="hidden-xs">
                  <%= room.temp.round(1) %>°
                </td>
                <td class="hidden-xs">
                  <%= room.humidity.round(1) %>%
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-xs-12 ">
      <h1 class="page_headline"> <%= "#{@room.name.split.map(&:capitalize).join(" ")}'s Room Details" %></h1>
      <hr>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= link_to building_path(@room.building.id), style: "font-size: 15px;" do %>
        <i class="fas fa-arrow-left"></i> To <%= @room.building.name.split.map(&:capitalize).join(" ") %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-sm-5 col-md-4">
      <div class="building_floorplan_outer">
        <div class="building_floorplan_inner">
          <img src="https://static1.squarespace.com/static/558b0741e4b06f25237894f2/t/5a90cd50c830257a34234405/1519439194245/unfurnished+(87).png?format=1500w" alt="">
        </div>
      </div>
      <hr class="hidden-sm hidden-md hidden-lg hidden-xl">
    </div>

    <div class="col-xs-12 col-sm-7 col-md-8">
      <div class="list_page_outer">
        <div class="list_page_inner">
          <table class="list_table table-condensed">
            <tr>
              <th></th>
              <th>Room Temp</th>
              <th>Room Humidity</th>
              <th class="hidden-xs">Room Size</th>
              <th>Ventilation Type</th>
              <th>Outside Air Vent.</th>
            </tr>
              <tr>
                <td></td>
                <td><%= @room.temp.round(1) %>°</td>
                <td><%= @room.humidity.round(1) %>%</td>
                <td class="hidden-xs"><%= @room.sqm %>m2</td>
                <td><%= @room.ventilation_type.name.capitalize %></td>
                <td><%= @room.outside_air_access == false ? "No" : "Yes" %></td>
              </tr>
          </table>
        </div>
      </div>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-xs-12 col-md-4">
      <h5 align="center" style="font-weight: bold; color: rgba(58,130,180,1) !important; text-decoration: underline;">Room Temp Log: Pasted 30 days</h5>
      <ul>
        <li>Avg. Temperature: <%= "#{(@inside_temp_array.reduce(:+) / @inside_temp_array.count).round(1)}°" %></li>
        <li>Avg. Humidity: <%= "#{(@inside_hum_array.reduce(:+) / @inside_hum_array.count).round(1)}%" %></li>
        <li>High Temperature: <%= "#{@inside_temp_array.sort.pop}°" %></li>
        <li>High Humidity: <%= "#{@inside_hum_array.sort.pop}%" %></li>
      </ul>
    </div>
    <div class="col-xs-12 col-md-8">
      <div class="bar_chart_container">
        <table>
          <tr>
            <% @inside_temp_array.each do |temp| %>
            <td title='<%= "#{temp}°" %>'>
              <div style='height: <%= "#{((1 - (temp / (@inside_temp_array.sort{ |x,y| y <=> x }.first) )) * 200).to_i}" %>px;'></div>
              <span class="hidden-xs"><%= "#{temp}" %></span>
            </td>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
  </div>

</div>

app/views/shared/_desktop_navbar.html.erb
<div class="wo_log-navbar wo_log-desktop-navbar hidden-xs">
  <nav class="">
    <div class="container-fluid">

      <%= render 'shared/home_button_mobile_button_navigation' %>

      <%= render 'shared/left_navigation' %>

      <%= render 'shared/right_navigation' %>

    </div>
  </nav>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible add-absolute-position" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible add-absolute-position" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer_container_outer">
  <div class="container">
    <div class="footer_container_inner">
      <div class="col-xs-12 col-md-4">
        <ul>
          <li><%= link_to(image_tag("soc_media/twitter.svg"), "#") %></li>
          <li><%= link_to(image_tag("soc_media/google.svg"), "#") %></li>
          <li><%= link_to(image_tag("soc_media/android.svg"), "#") %></li>
          <li><%= link_to(image_tag("soc_media/facebook.svg"), "#") %></li>
          <li><%= link_to(image_tag("soc_media/linkedin.svg"), "#") %></li>
        </ul>
      </div>
      <div class="col-xs-12 col-md-4 hidden-xs">
        <%= "<h5>Copyright &copy;&nbsp;&nbsp;|&nbsp;&nbsp;#{Date.today}</h5>".html_safe %>
      </div>
      <div class="col-xs-12 col-md-4">
        <ul>
          <li><%= link_to(image_tag("soc_media/contact.svg"), "#") %></li>
          <li><%= link_to(image_tag("soc_media/map.svg"), "#") %></li>
        </ul>
      </div>
      <div class="col-xs-12 col-md-4 hidden-xl hidden-lg hidden-md hidden-sm">
        <%= "<h5>Copyright &copy;&nbsp;&nbsp;|&nbsp;&nbsp;#{Date.today}</h5>".html_safe %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_home_button_mobile_button_navigation.html.erb
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <!-- <i class="fa fa-bars dropdown-toggle"></i> -->
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <%= link_to my_acs_path, class: "nav-home-link" do %>
      <span class="brand_font_nav"><i class="fas fa-tachometer-alt"></i>ACS</span></span>
    <% end %>
  </div>

app/views/shared/_left_navigation.html.erb
<% if user_signed_in? %>
  <ul class="nav navbar-nav">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="brand_font_nav">MY ACS</span> <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Dashboard", my_acs_path %></li>
        <% @all_buildings.each do |building| %>
        <li><%= link_to building.name.split.map(&:capitalize).join(" "), building_path(building.id) %></li>
        <% end %>
      </ul>
    </li>
      <li><a href="#">Link</a></li>
      <li><a href="#">One More Link</a></li>
  </ul>
<% else %>
<% end %>

app/views/shared/_mobile_navbar.html.erb
<div class="wo_log-navbar wo_log-mobile-navbar hidden-sm hidden-md hidden-lg hidden-xl">
  <nav class="">
    <div class="container-fluid">

      <%= render 'shared/home_button_mobile_button_navigation' %>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">

        <%= render 'shared/left_navigation' %>

        <%= render 'shared/right_navigation' %>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</div>

app/views/shared/_navbar.html.erb
<div class="">
  <!-- Logo -->
  <%= link_to root_path, class: "" do %>
    <h4>Home link</h4>
  <% end %>

  <!-- Right Navigation -->

    <% if user_signed_in? %>
      <h4>You're signed in asshole</h4>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "" %>
    <% end %>

  <!-- Dropdown list appearing on mobile only -->
  <div class="hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right">
        <li><a href="#">LINK</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_right_navigation.html.erb
    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>

      </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to new_user_session_path, class: "" do %>
            <i class="fas fa-sign-in-alt"></i> <%= t(".sign_in", default: "Log in") %>
          <% end %>
        </li>
      </ul>
    <% end %>